version: '3.8'
services:

  zoo-1:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zoo-1
    hostname: zoo-1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # volumes:
    #   - ./volume/zookeeper/data:/data
    #   - ./volume/zookeeper/datalog:/datalog
    networks:
      - kakfa-net

  kafka-1:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # volumes:
    #   - ./volume/kafka/data:/var/lib/kafka/data
    depends_on:
      - zoo-1
    networks:
      - kakfa-net

  mongodb-1:
    image: mongo:5.0.3-focal
    container_name: mongodb-1
    hostname: mongodb1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my_password
    networks:
      - kakfa-net
    # volumes:
    #   - ./volume/mongo-data:/data/db
    #   - ./volume/mongo-config:/data/configdb

  mongo-express-1:
    image: mongo-express:0.54.0
    container_name: mongo-express-1
    hostname: mongo-express1
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
      ME_CONFIG_MONGODB_SERVER: mongodb1   
    depends_on:
      - mongodb-1
    networks:
      - kakfa-net

networks:
  kakfa-net: